# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       debota-utilities

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    QuickBar utilities
Version:    0.4
Release:    12
Group:      Qt/Qt
License:    LICENSE
Source100:  debota-utilities.yaml

%description
QuickBar utilities, including : autostart


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> uninstall pre
%preun
systemctl-user disable %{_sysconfdir}/systemd/user/harbour-debota.service
# << uninstall pre

# >> install post
%post
systemctl-user enable %{_sysconfdir}/systemd/user/harbour-debota.service
# << install post


%files
%defattr(-,root,root,-)
%{_datadir}/dbus-1/services/com.giuliettasw.debota.service
%{_sysconfdir}/systemd/user/harbour-debota.service
# >> files
# << files
